### ISSUE TITLE
Chat window on Item Piles causes styling issues

### ISSUE THREAD

**Issue by drywallmud** [FoxLee/fox-4e-styling#19]
Hi,

Using Item Piles to set up Merchants in 4e, and it seems to work, but the transparent background on the chat records is not readable. If its an easy fix, could you do what you did with Narrator Tools with Item Piles as well?

![image](https://user-images.githubusercontent.com/5306827/232260890-47a4b31f-5a80-4f35-a7c0-a58af5cd2abd.png)

Thanks again for all you do!

**Comment by FoxLee** [comment]
Hey hey! It was a bit trickier than expected because of where Item Piles provides its classes (so late! <XD). Also because Item Piles and Chat Portrait do not get along. But I got there! I think I made something that looks fine and is workable for both at once. Expect it in the next update—shouldn't be too long :)

**Comment by drywallmud** [comment]
Just grateful you made it work, I'm sure it's amazing! Thanks again!

**Comment by FoxLee** [comment]
Wow, I totally forgot to publish these changes after getting it done >3>; Sorry, I've been a bit scatterbrained lately. v0.9.46-beta contains Item Piles support :)
